#!/bin/sh

# Uptime-Kuma FreeBSD Service Script

# PROVIDE: uptimekuma
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

load_rc_config $name

: ${uptimekuma_enable:="NO"}
: ${uptimekuma_config:="--name uptime-kuma -- --port=3001 --host=0.0.0.0"}
: ${uptimekuma_env:="PLAYWRIGHT_BROWSERS_PATH=/nonexistent"}

name="uptimekuma"
rcvar="uptimekuma_enable"
pidfile="/var/run/${name}/${name}.pid"
command="/usr/sbin/daemon"
procname="/usr/local/bin/node"
proccommand="/usr/local/uptime-kuma/server/server.js"
command_args="-r -u ${name} -P ${pidfile} ${procname} ${proccommand} ${uptimekuma_config}"
PATH=${PATH}:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
export LC_CTYPE="en_US.UTF-8"

run_rc_command "$1"
