#!/bin/sh

# Uptime-Kuma FreeBSD Service Script

# PROVIDE: uptimekuma
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

load_rc_config $name

: ${uptimekuma_enable:="NO"}
: ${uptimekuma_chdir:="/usr/local/uptime-kuma/node_modules"}
: ${uptimekuma_config:="--name uptime-kuma -- --port=3001 --host=0.0.0.0"}
: ${uptimekuma_env:="PLAYWRIGHT_BROWSERS_PATH=/nonexistent"}

name="uptimekuma"                                                                                   
rcvar="uptimekuma_enable"
command="/usr/sbin/daemon"
pidfile="/var/run/uptimekuma/uptimekuma.pid"
procname="/usr/local/bin/node /usr/local/uptime-kuma/server/server.js"
PATH=${PATH}:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin                 
export LC_CTYPE="en_US.UTF-8"                                                                       
command_args="-r -u ${name} -P ${pidfile} ${procname} ${uptimekuma_config}"

run_rc_command "$1"
